apiVersion: v1
kind: Namespace
metadata:
  name: schemahero-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: schema-hero
  namespace: flux-system
spec:
  interval: 3s
  targetNamespace: schemahero-system
  sourceRef:
    kind: GitRepository
    name: idp-demo
  path: "schema-hero"
  prune: true
