---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: idp-demo
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/abangser-org/idp-demo
  ref:
    branch: main
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: idp-demo
  namespace: production
spec:
  interval: 5m0s
  url: https://github.com/abangser-org/idp-demo
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: idp-production-apps
  namespace: flux-system
spec:
  interval: 3s
  sourceRef:
    kind: GitRepository
    name: idp-demo
  path: "apps"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: idp-production-infra
  namespace: flux-system
spec:
  interval: 3s
  sourceRef:
    kind: GitRepository
    name: idp-demo
  path: "infra"
  prune: true
